/*
 * MessageWindow.java
 *
 * Created on June 2, 2001, 11:42 PM
 *
 * $Id: MessageWindow.java,v 1.1 2004/04/02 06:01:59 sdchen Exp $
 *
 *============================================================================
 *
 * Copyright (C) 2001  Steven D. Chen
 *
 * This file is part of jQuizShow.
 *
 * jQuizShow is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * jQuizShow is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License (GPL)
 * along with jQuizShow; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *============================================================================
 *
 * Modifications:
 *
 *    $Log: MessageWindow.java,v $
 *    Revision 1.1  2004/04/02 06:01:59  sdchen
 *    Snapshot of jQuizShow 1.1 alpha06 development
 *
 *    Revision 1.2  2002/08/15 04:43:26  sdchen
 *    Internationalization of source code.  Main.getMessage() is the primary
 *    routine to get the localized message strings.
 *
 *    Revision 1.1.1.1  2002/04/13 17:01:40  sdchen
 *    Initial import of the jQuizShow sources from local development directory.
 *
 *
 */

package jQuizShow;

/**
 *
 * @author  Steven D. Chen
 */

import javax.swing.*;


public class MessageWindow extends javax.swing.JInternalFrame {

    /** Creates new form MessageWindow */
    public MessageWindow() {
        super(Main.getMessage("title_message_window"), true, true, true,
		true);

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        
        initComponents();
        setSize(500,300);
        
        m_vertScrollBar = jScrollPane1.getVerticalScrollBar();
    }

    /**
     * Returns the JTextArea contained in this frame.
     */
    public void  append(String  text) {
        m_text.append(text);

        m_vertScrollBar.setValue(m_vertScrollBar.getMaximum() - m_vertScrollBar.getVisibleAmount());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        m_text = new javax.swing.JTextArea();
        
        m_text.setDisabledTextColor(java.awt.Color.black);
        m_text.setEnabled(false);
        jScrollPane1.setViewportView(m_text);
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea m_text;
    // End of variables declaration//GEN-END:variables

    private JScrollBar  m_vertScrollBar;
}
